version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - TZ=${TZ:-Asia/Kolkata}

volumes:
  n8n_data: